#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the five macOS signing secrets of the signed DMG job.
# Nothing here goes to .env: every value is a GitHub secret only.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
# The Apple Developer Team ID of the certificate that signs the DMG. It is
# not a secret (every signed binary carries it), but it belongs to whoever
# runs the release, so stage 1 asks for it.
TEAM_ID="${APPLE_TEAM_ID:-}"
CERT_NAME="Developer ID Application"
ENV_FILE="$(mktemp)"   # the library needs one; nothing is written to it
trap 'rm -f "$ENV_FILE"' EXIT

has_identity() {
  security find-identity -v -p codesigning 2>/dev/null | grep -q "$CERT_NAME.*($TEAM_ID)"
}

banner "macOS signing secrets for the signed DMG"

# ── 1. The certificate ────────────────────────────────────────────────────
stage "Developer ID Application certificate"
if [[ -z "$TEAM_ID" ]]; then
  say "The Team ID is the ten characters Apple shows under Membership details."
  ask TEAM_ID "Your Apple Developer Team ID:"
  until [[ "$TEAM_ID" =~ ^[A-Z0-9]{10}$ ]]; do
    warn "A Team ID is ten upper-case letters and digits."
    ask TEAM_ID "Your Apple Developer Team ID:"
  done
fi
if has_identity; then
  say "The login keychain already holds a $CERT_NAME certificate of team $TEAM_ID."
  pause
else
  say "The keychain has no $CERT_NAME certificate of team $TEAM_ID (the Apple Distribution one signs App Store builds only)."
  say "Only the Account Holder of the team can make this certificate."
  step "Keychain Access → Certificate Assistant → Request a Certificate From a Certificate Authority."
  step "Fill your email and name, choose 'Saved to disk', and save the CertificateSigningRequest file."
  open_url "https://developer.apple.com/account/resources/certificates/add"
  step "Choose '$CERT_NAME', upload the request file, and download the .cer file."
  step "Double-click the .cer file: it lands in the login keychain beside its private key."
  pause "Done? Press Enter to check the keychain."
  until has_identity; do
    warn "No '$CERT_NAME' identity of team $TEAM_ID is in the keychain yet."
    pause "Install it, then press Enter to check again."
  done
  say "Found it."
fi

# ── 2. The .p12 ───────────────────────────────────────────────────────────
stage "Export the certificate as a .p12"
step "Keychain Access → My Certificates → right-click the '$CERT_NAME' certificate of team $TEAM_ID → Export."
step "Keep the format 'Personal Information Exchange (.p12)' and set a password for the file."
ask P12_PATH "Path of the exported .p12 file:"
P12_PATH="${P12_PATH/#\~/$HOME}"
until [[ -f "$P12_PATH" ]]; do
  warn "No file at $P12_PATH."
  ask P12_PATH "Path of the exported .p12 file:"
  P12_PATH="${P12_PATH/#\~/$HOME}"
done
ask_secret CSC_KEY_PASSWORD "The password of the .p12:"
until openssl pkcs12 -in "$P12_PATH" -nokeys -passin "pass:$CSC_KEY_PASSWORD" -legacy >/dev/null 2>&1 \
   || openssl pkcs12 -in "$P12_PATH" -nokeys -passin "pass:$CSC_KEY_PASSWORD" >/dev/null 2>&1; do
  warn "That password does not open the .p12."
  ask_secret CSC_KEY_PASSWORD "The password of the .p12:"
done
CSC_LINK="$(base64 -i "$P12_PATH" | tr -d '\n')"
set_secret CSC_LINK "$CSC_LINK"
set_secret CSC_KEY_PASSWORD "$CSC_KEY_PASSWORD"
if confirm "Delete $P12_PATH now that it is a secret?"; then rm -f "$P12_PATH"; say "Deleted."; fi

# ── 3. The notarizing account ─────────────────────────────────────────────
stage "The Apple ID that notarizes"
say "Notarization signs in with an Apple ID of the team and an app-specific password."
ask APPLE_ID "The Apple ID (email) that notarizes:"
open_url "https://account.apple.com/account/manage"
step "Sign-In and Security → App-Specific Passwords → Generate. Name it 'pagis notarization'."
step "Copy the password Apple shows; it is shown once."
ask_secret APPLE_APP_SPECIFIC_PASSWORD "The app-specific password:"
set_secret APPLE_ID "$APPLE_ID"
set_secret APPLE_APP_SPECIFIC_PASSWORD "$APPLE_APP_SPECIFIC_PASSWORD"

# ── 4. The team ───────────────────────────────────────────────────────────
stage "The team"
say "The certificate belongs to team $TEAM_ID."
set_secret APPLE_TEAM_ID "$TEAM_ID"

# ── 5. Check ──────────────────────────────────────────────────────────────
stage "Check"
say "The signed DMG job reads exactly these five secrets:"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh secret list 2>/dev/null | sed 's/^/    /'
fi
say "A 'v*' tag now signs, notarizes and publishes the DMG. Try it:"
note "    git tag v<version> && git push origin v<version>"
pause

finish
