//! `cargo xtask emergency-numbers`: the generator behind the emergency
//! number table (ADR-0018).
//!
//! The table is a constant of the program, like the migrations and the
//! interface bundle. It never enters the user's database. The source is
//! libphonenumber's metadata (Apache-2.0) at one pinned release tag:
//! `ShortNumberMetadata.xml` carries the emergency pattern of each
//! territory, and `PhoneNumberMetadata.xml` carries the calling code
//! that maps a held number to its territory. No Rust crate implements
//! libphonenumber's `ShortNumberInfo`, so Pagis compiles the patterns
//! in itself.
//!
//! Generation is a dev-time step. The command fetches both files with
//! `curl`, caches them under `target/`, and writes the table. With
//! `--check` it writes nothing and fails when the checked-in table is
//! not what the generator produces, which is how `cargo xtask full`
//! catches a hand edit or a generator change without a regeneration.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};

/// The libphonenumber release the table is generated from. Bump it and
/// run the command to take a newer table.
pub const LIBPHONENUMBER_TAG: &str = "v9.0.38";

/// Where the generated table lives, relative to the workspace root.
pub const TABLE_PATH: &str = "crates/pagis-telephony/src/emergency/table.rs";

const PHONE_METADATA: &str = "PhoneNumberMetadata.xml";
const SHORT_METADATA: &str = "ShortNumberMetadata.xml";

/// Generate the table source from the two metadata files.
///
/// Every geographic territory of `PhoneNumberMetadata.xml` gets a row,
/// with its emergency pattern from `ShortNumberMetadata.xml` when it
/// has one. A territory that shares its calling code is marked main
/// only when upstream marks it so; a territory alone on its code is
/// main by itself. Rows are sorted by region, so a diff between two
/// tags reads.
pub fn generate_table(tag: &str, phone_xml: &str, short_xml: &str) -> Result<String> {
    let mut territories = parse_calling_codes(phone_xml)?;
    for (region, pattern) in parse_emergency_patterns(short_xml)? {
        let Some(territory) = territories.get_mut(&region) else {
            bail!("{SHORT_METADATA} has territory {region}, which {PHONE_METADATA} lacks");
        };
        territory.emergency = Some(pattern);
    }
    let mut code_counts: BTreeMap<u16, usize> = BTreeMap::new();
    for territory in territories.values() {
        *code_counts.entry(territory.calling_code).or_default() += 1;
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! Generated by `cargo xtask emergency-numbers` from libphonenumber {tag}"
    );
    let _ = writeln!(
        out,
        "//! (`resources/{PHONE_METADATA}` and `resources/{SHORT_METADATA}`, Apache-2.0)."
    );
    out.push_str("//! Do not edit by hand: run the command again.\n\n");
    out.push_str("use super::Territory;\n\n");
    out.push_str("/// The libphonenumber release the rows come from.\n");
    let _ = writeln!(out, "pub const SOURCE_VERSION: &str = \"{tag}\";\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const TERRITORIES: &[Territory] = &[\n");
    for (region, territory) in &territories {
        let main_for_code = territory.main_for_code || code_counts[&territory.calling_code] == 1;
        let emergency = match &territory.emergency {
            Some(pattern) => format!("Some(\"{}\")", pattern.replace('\\', "\\\\")),
            None => "None".to_string(),
        };
        let _ = writeln!(
            out,
            "    Territory {{ region: \"{region}\", calling_code: {}, main_for_code: {main_for_code}, emergency: {emergency} }},",
            territory.calling_code
        );
    }
    out.push_str("];\n");
    Ok(out)
}

/// Fetch the metadata at `tag`, or read it from the cache under
/// `target/`, and write the table. With `check`, compare instead.
pub fn run(root: &Path, check: bool) -> Result<()> {
    let phone_xml = fetch(root, LIBPHONENUMBER_TAG, PHONE_METADATA)?;
    let short_xml = fetch(root, LIBPHONENUMBER_TAG, SHORT_METADATA)?;
    let table = generate_table(LIBPHONENUMBER_TAG, &phone_xml, &short_xml)?;
    let path = root.join(TABLE_PATH);
    if check {
        let current = std::fs::read_to_string(&path)
            .with_context(|| format!("cannot read {}", path.display()))?;
        if current != table {
            bail!(
                "{TABLE_PATH} is not what the generator produces from libphonenumber {LIBPHONENUMBER_TAG}; run `cargo xtask emergency-numbers`"
            );
        }
        println!("{TABLE_PATH} matches libphonenumber {LIBPHONENUMBER_TAG}");
        return Ok(());
    }
    std::fs::write(&path, table).with_context(|| format!("cannot write {}", path.display()))?;
    println!("wrote {TABLE_PATH} from libphonenumber {LIBPHONENUMBER_TAG}");
    Ok(())
}

struct TerritoryRow {
    calling_code: u16,
    main_for_code: bool,
    emergency: Option<String>,
}

/// The calling code of every geographic territory. The `001` entries
/// are non-geographic services (satellite, international toll-free)
/// and no number Pagis holds lives there.
fn parse_calling_codes(xml: &str) -> Result<BTreeMap<String, TerritoryRow>> {
    let document = parse_xml(xml).context("cannot parse PhoneNumberMetadata")?;
    let mut territories = BTreeMap::new();
    for node in territory_nodes(&document) {
        let region = territory_id(&node)?;
        if region == "001" {
            continue;
        }
        let calling_code = node
            .attribute("countryCode")
            .with_context(|| format!("territory {region} has no countryCode"))?
            .parse::<u16>()
            .with_context(|| {
                format!("territory {region} has a countryCode that is not a number")
            })?;
        let main_for_code = node.attribute("mainCountryForCode") == Some("true");
        if territories
            .insert(
                region.to_string(),
                TerritoryRow {
                    calling_code,
                    main_for_code,
                    emergency: None,
                },
            )
            .is_some()
        {
            bail!("{PHONE_METADATA} lists territory {region} twice");
        }
    }
    if territories.is_empty() {
        bail!("{PHONE_METADATA} has no territories");
    }
    Ok(territories)
}

/// The emergency pattern of every territory that has one, with the
/// whitespace upstream uses for layout removed.
fn parse_emergency_patterns(xml: &str) -> Result<Vec<(String, String)>> {
    let document = parse_xml(xml).context("cannot parse ShortNumberMetadata")?;
    let mut patterns = Vec::new();
    for node in territory_nodes(&document) {
        let region = territory_id(&node)?;
        let Some(emergency) = node
            .children()
            .find(|child| child.has_tag_name("emergency"))
        else {
            continue;
        };
        let pattern = emergency
            .children()
            .find(|child| child.has_tag_name("nationalNumberPattern"))
            .and_then(|pattern| pattern.text())
            .with_context(|| {
                format!("territory {region} has an emergency element with no pattern")
            })?;
        let pattern: String = pattern.chars().filter(|c| !c.is_whitespace()).collect();
        if pattern.is_empty() {
            bail!("territory {region} has an empty emergency pattern");
        }
        patterns.push((region.to_string(), pattern));
    }
    Ok(patterns)
}

/// Both files open with a DTD, which roxmltree refuses by default.
fn parse_xml(xml: &str) -> Result<roxmltree::Document<'_>> {
    let options = roxmltree::ParsingOptions {
        allow_dtd: true,
        ..Default::default()
    };
    Ok(roxmltree::Document::parse_with_options(xml, options)?)
}

fn territory_nodes<'a>(
    document: &'a roxmltree::Document<'a>,
) -> impl Iterator<Item = roxmltree::Node<'a, 'a>> {
    document
        .descendants()
        .filter(|node| node.has_tag_name("territory"))
}

fn territory_id<'a>(node: &roxmltree::Node<'a, '_>) -> Result<&'a str> {
    node.attribute("id")
        .context("a territory element has no id")
}

/// One metadata file at `tag`, from the cache or from GitHub.
fn fetch(root: &Path, tag: &str, file: &str) -> Result<String> {
    let cached = cache_path(root, tag, file);
    if let Ok(body) = std::fs::read_to_string(&cached) {
        return Ok(body);
    }
    let url =
        format!("https://raw.githubusercontent.com/google/libphonenumber/{tag}/resources/{file}");
    std::fs::create_dir_all(cached.parent().expect("cache file has a parent"))?;
    let status = Command::new("curl")
        .args(["--silent", "--show-error", "--fail", "--location", &url])
        .arg("--output")
        .arg(&cached)
        .status()
        .context("cannot run curl; install it to fetch libphonenumber")?;
    if !status.success() {
        let _ = std::fs::remove_file(&cached);
        bail!("cannot fetch {url}");
    }
    std::fs::read_to_string(&cached).with_context(|| format!("cannot read {}", cached.display()))
}

fn cache_path(root: &Path, tag: &str, file: &str) -> PathBuf {
    root.join("target")
        .join("libphonenumber")
        .join(tag)
        .join(file)
}
